image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  GITLAB_CI_ENV: production

  TF_ROOT: ${CI_PROJECT_DIR}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${GITLAB_CI_ENV}

  # TF_VAR_PROJECT_ID: ${{ secrets.TF_VAR_PROJECT_ID }}
  # TF_VAR_IP_ADDR: ${{ secrets.TF_VAR_IP_ADDR }}
  # TF_VAR_SSH_USER: ${{ secrets.TF_VAR_SSH_USER }}
  # TF_VAR_SSH_PUB_KEY: ${{ secrets.TF_VAR_SSH_PUB_KEY }}

cache:
  key: ${GITLAB_CI_ENV}
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}

stages:
  - prepare
  - validate
  - build
  - deploy

init:
  stage: prepare
  script:
    - gitlab-terraform init

validate:
  stage: validate
  script:
    - gitlab-terraform validate

plan:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: deploy
  environment:
    name: ${GITLAB_CI_ENV}
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  when: manual
  only:
    - master
